config/routes.rb
Rails.application.routes.draw do
  resources :menu_orders
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :menus
  resources :menu_orders do
    put :update_attribute, defaults: { format: 'js' }
  end

  get 'employees', to: 'views#employees'
  get 'calculation', to: 'views#calculation'
  get 'info', to: 'views#info'
  put 'views/update_employee', to: 'views#update_employee'
  delete 'views/delete_employee', to: 'views#delete_employee'

  root to: 'views#home'
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :menu_orders, dependent: :destroy
    before_save :set_default
    scope :active, -> {where('lunch_date > ?', Date.today)}
    scope :orderable, -> {where('due_date > ?', DateTime.now)}
    scope :passed, -> {where('lunch_date < ?', Date.today)}
    validates :lunch_date, uniqueness: true

    protected
    def set_default
        self.soup = self.soup || "Nema"
        self.main_course = self.main_course || "Nema"
        self.side1 = self.side1 || "Nema"
        self.side2 = self.side2 || "Nema"
        if self.lunch_date.wday == 1
            d=self.lunch_date-3
        else
            d=self.lunch_date-1
        end
        
        self.due_date = Time.zone.local(d.year, d.month, d.day, 14, 0, 0)
    end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :clean_passed
  # GET /menus
  # GET /menus.json
  def index
    @menus_active=Menu.active.order(lunch_date: :asc)
    @menus_passed=Menu.passed.order(lunch_date: :asc)
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu_orders=@menu.menu_orders.ordered
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)
    @employees = Employee.where(admin: false)
    respond_to do |format|
      if @menu.save
        @employees.each do |e|
          MenuOrder.create(employee_id: e.id, menu_id: @menu.id, soup: 0, main_course: 0, side1: 0, side2: 0, beetroot: 0, cabbage: 0, lettuce: 0, bread: 0)
        end
        format.html { redirect_to menus_url, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:soup, :soup_p, :main_course, :main_p, :side1, :side1_p, :side2, :side2_p, :lunch_date, :due_date, :description)
    end

    def authorize
      if not current_employee.admin?
        redirect_to root_url
      end
    end
    def clean_passed
      Menu.passed.destroy_all
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <div class="field">
      <%= form.label "Juha" %>
      <%= form.text_field :soup %>
    </div>
    <div class="field">
      <%= form.label "Cijena juhe" %>
      <%= form.text_field :soup_p %>
    </div>
    <div class="field">
      <%= form.label "Glavno jelo" %>
      <%= form.text_field :main_course %>
    </div>
    <div class="field">
      <%= form.label "Cijena glavnog jela" %>
      <%= form.text_field :main_p %>
    </div>
    <div class="field">
      <%= form.label "Prilog 1" %>
      <%= form.text_field :side1 %>
    </div>

    <div class="field">
      <%= form.label "Cijena priloga 1" %>
      <%= form.text_field :side1_p %>
    </div>
    <div class="field">
      <%= form.label "Prilog 2" %>
      <%= form.text_field :side2 %>
    </div>

    <div class="field">
      <%= form.label "Cijena priloga 2" %>
      <%= form.text_field :side2_p %>
    </div>

    <div class="field">
      <%= form.label "Datum ručka" %>
      <%= form.date_select :lunch_date %>
    </div>

    <div class="field">
      <%= form.label "Napomena" %>
      <%= form.text_field :description %>
    </div>

    <div class="actions">
      <%= form.submit "Spremi Meni", class: "button button-add" %>
      <%= link_to 'Odustani', menus_path, class: "button button-clear"%>
    </div>
  </div>
<% end %>

app/views/menus/edit.html.erb
<div class="table">

    <h1>Prepravi meni <%=@menu.lunch_date.strftime("%d.%m.%Y")%></h1>
    <br>
    <%= render 'form', menu: @menu %>

</table>

app/views/menus/index.html.erb
<div class="table">

  <h1>Meniji <%= link_to 'Dodaj novi meni', new_menu_path, class: "button button-add" %></h1>

  <table>
    <thead>
      <tr>
        <th>Datum ručka</th>
        <th>Napomena</th>
        <th>Juha</th>
        <th>Glavno jelo</th>
        <th>Prilog 1</th>
        <th>Prilog 2</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @menus_active.each do |menu| %>
        <tr>
          <td><%= menu.lunch_date.strftime("%d.%m.%Y") %></td>
          <td><%= menu.description %></td>
          <td><%= menu.soup %></td>
          <td><%= menu.main_course %></td>
          <td><%= menu.side1 %></td>
          <td><%= menu.side2 %></td>
          <td><%= link_to 'Prikaži', menu, class: "button button-add"  %>
            <%= link_to 'Uredi', edit_menu_path(menu), class: "button button-add"  %>
            <%= link_to 'Obriši', menu, method: :delete, data: { confirm: 'Are you sure?' }, class: "button button-clear" %></td>
        </tr>

      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/menus/new.html.erb
<div class="table">

    <h1>Novi Meni</h1>
    <br>
    <%= render 'form', menu: @menu %>

</table>

app/views/menus/show.html.erb
<div class="table">

  <h2> <%=@menu.lunch_date.strftime("%d.%m.%Y") %> <%= link_to 'Uredi', edit_menu_path(@menu), class: "button button-add" %> <%= link_to 'Nazad', menus_path, class: "button button-clear" %> </h2>
  <p>
    <strong>Rok za prijavu ručka:</strong>
    <%= @menu.due_date.strftime("%d.%m.%Y %H:%M") %>
  </p>

  <p>
    <strong>Opis obroka (datum):</strong>
    <%= @menu.description %>
  </p>

  <table>
    <tr>
      <th>Ime</th>
      <th>Juha (<%=@menu.soup%>)</th>
      <th>Glavno jelo (<%=@menu.main_course%>)</th>
      <th>Prilog 1 (<%=@menu.side1%>)</th>
      <th>Prilog 2 (<%=@menu.side2%>)</th>
      <th>Cikla</th>
      <th>Kupus</th>
      <th>Zelena salata</th>
      <th>Kruh</th>
    </tr>
    <%@menu_orders.each do |menu_order|%>
      <tr>
        <td><%= menu_order.employee.full_name %></td>
        <td><%= menu_order.soup %></td>
        <td><%= menu_order.main_course %></td>
        <td><%= menu_order.side1 %></td>
        <td><%= menu_order.side2 %></td>
        <td><%= menu_order.beetroot %></td>
        <td><%= menu_order.cabbage %></td>
        <td><%= menu_order.lettuce %></td>
        <td><%= menu_order.bread %></td>
      </tr>
    <%end%>

    <br>
    <tr>
      <td style="font-weight: bold;">Ukupno: </td>
      <td><%= @menu_orders.sum(:soup) %></td>
      <td><%= @menu_orders.sum(:main_course)  %></td>
      <td><%= @menu_orders.sum(:side1)  %></td>
      <td><%= @menu_orders.sum(:side2)  %></td>
      <td><%= @menu_orders.sum(:beetroot) %></td>
      <td><%= @menu_orders.sum(:cabbage)  %></td>
      <td><%= @menu_orders.sum(:lettuce)  %></td>
      <td><%= @menu_orders.sum(:bread)  %></td>
    </tr>
  </table>
</div>