config/routes.rb
Rails.application.routes.draw do
  resources :menu_orders
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :menus
  resources :menu_orders do
    put :update_attribute, defaults: { format: 'js' }
  end

  get 'employees', to: 'views#employees'
  get 'calculation', to: 'views#calculation'
  get 'info', to: 'views#info'
  put 'views/update_employee', to: 'views#update_employee'
  delete 'views/delete_employee', to: 'views#delete_employee'

  root to: 'views#home'
end

app/views/views/calculation.html.erb
<div class="table">
  <h1>Obračun za <%=@date.strftime("%m.%Y.")%></h1>
  <%date=Date.current-1.months%>
  <div class="form-tag">
    <%= form_tag(calculation_path, method: :get ) do |f| %>
      <%=select_date(date, order: [:year, :month], start_year: 2020, end_year: Date.today.year)%>
      <%=submit_tag 'Generiraj Obračun', class: "button button-add"%>
    <%end%>
  </div>
  <table>
    <tr>
      <th>Ime</th>
      <th>Potrošeno (kn)</th>
    </tr>
    <%@employees.each do |employee|%>
      <tr>
        <td><%= employee.full_name %></td>
        <td class="sum"><%= sprintf("%.2f",employee.get_calculation(@date)) %></td>
      </tr>
    <%end%>
    <br>
    <tr>
      <td style="font-weight: bold;">Ukupno: </td>
      <td id="sum"></td>
    </tr>
  </table>
</div>

<script>
  (function() {
    var sum=0;
    var els = document.getElementsByClassName("sum");
    Array.from(els).forEach((el) => {
      sum+=parseFloat(el.textContent);
    });
    document.getElementById("sum").textContent=sum.toFixed(2);
  })();
</script>

app/views/views/employees.html.erb
<div class="table">
    <h2>Korisnici <%= link_to 'Nazad', menus_path, class: "button button-clear" %> </h2>
 
    <table>
        <thead>
        <tr>
            <th>Ime Zaposlenika</th>
            <th>Email</th>
            <th colspan="2">Akcije</th>
        </tr>
        </thead>

        <tbody>
            <% @employees.each do |employee| %>
                <tr>
                    <td><%=employee.full_name%></td>
                    <td><%=employee.email%></td>
                    <td>
                        <% if employee.approved %>
                            <%=link_to 'Zabrani', views_update_employee_path(employee_id: employee.id, update_param: "Disapprove"), method: :put, class: "button button-clear"%>
                        <%else%>
                            <%= link_to 'Odobri', views_update_employee_path(employee_id: employee.id, update_param: "Approve"), method: :put, class: "button button-add"%>
                        <%end%>
                    </td>
                    <td> <%=link_to 'Obriši', views_delete_employee_path(employee_id: employee.id), method: :delete, class: "button button-clear"%>  </td>
                </tr>
            <%end%>
    </tabe>
</div>

app/views/views/home.html.erb

<%@menus.each do |m|%>
    
    <div class="table">
        <h1><%=m.lunch_date.strftime("%d.%m.%Y")%></h1>
        <p><%=m.description%></p>           
        <table>
            <tr>
                <%if m.soup!="Nema"%><th><%=m.soup%> (<%=m.soup_p%> kn)</th><%end%>
                <%if m.main_course!="Nema"%><th><%=m.main_course%> (<%=m.main_p%> kn)</th><%end%>
                <%if m.side1!="Nema"%><th><%=m.side1%> (<%=m.side1_p%> kn)</th><%end%>
                <%if m.side2!="Nema"%><th><%=m.side2%> (<%=m.side2_p%> kn)</th><%end%>
                <th>Cikla (<%=m.beetroot_p%> kn)</th>
                <th>Kupus (<%=m.cabbage_p%> kn)</th>
                <th>Zelena salata (<%=m.lettuce_p%> kn)</th>
                <th>Kruh (<%=m.bread_p%> kn)</th>
                <th>Cijena</th>
                <th></th>
            </tr>
            <%m.menu_orders.where(employee_id: current_employee.id).each do |mo|%>
                <tr>
                    <%if m.soup!="Nema"%><td>
                        <p id="<%=m.id%>-<%=mo.id%>-soup"><%=mo.soup%></p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "soup"), method: :put, remote: true, class: "button button-add"%>
                    </td><%end%>
                    <%if m.main_course!="Nema"%><td>
                        <p id="<%=m.id%>-<%=mo.id%>-main"><%=mo.main_course%></p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "main"), method: :put, remote: true, class: "button button-add"%>
                    </td><%end%>
                    <%if m.side1!="Nema"%><td>
                        <p id="<%=m.id%>-<%=mo.id%>-side1"><%=mo.side1%></p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "side1"), method: :put, remote: true, class: "button button-add"%>
                    </td><%end%>
                    <%if m.side2!="Nema"%><td>
                        <p id="<%=m.id%>-<%=mo.id%>-side2"><%=mo.side2%></p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "side2"), method: :put, remote: true, class: "button button-add"%>
                    </td><%end%>
                    <td>
                        <p id="<%=m.id%>-<%=mo.id%>-beetroot"><%=mo.beetroot%> </p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "beetroot"), method: :put, remote: true, class: "button button-add"%>
                    </td>
                    <td> 
                        <p id="<%=m.id%>-<%=mo.id%>-cabbage"><%=mo.cabbage%> </p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "cabbage"), method: :put, remote: true, class: "button button-add"%>
                    </td>
                    <td>
                        <p id="<%=m.id%>-<%=mo.id%>-lettuce"><%=mo.lettuce%> </p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "lettuce"), method: :put, remote: true, class: "button button-add"%>
                    </td>
                    <td>
                        <p id="<%=m.id%>-<%=mo.id%>-bread"><%=mo.bread%></p>
                        <%=link_to "Dodaj", menu_order_update_attribute_path(mo, update_action: "bread"), method: :put, remote: true, class: "button button-add"%>
                    </td>
                    <td id="<%=m.id%>-<%=mo.id%>-price"><%=(mo.soup*m.soup_p + 
                                                            mo.main_course*m.main_p + 
                                                            mo.side1*m.side1_p + 
                                                            mo.side2*m.side2_p + 
                                                            mo.beetroot*m.beetroot_p + 
                                                            mo.cabbage*m.cabbage_p + 
                                                            mo.lettuce*m.lettuce_p + 
                                                            mo.bread*m.bread_p).round(2)     %> kn</td>
                    <td>
                        <div id="clear-order-button">
                            <%= link_to "Očisti", menu_order_update_attribute_path(mo, update_action: "clear"), method: :put, remote: true, class: "button button-clear"%>                        
                        </div>
                    </td>
                </tr>
            <%end%>
        </table>
    </div>
<%end%>

app/views/views/info.html.erb
<div class="table">
  <h1>Današnja narudžba (<%=Date.today.strftime("%d.%m.%Y.")%>)</h1>
  <%if !@today or @today.not_ordered%>
    <h3>Nema narudžbe!</h3>
  <%else%>
    <%if @today.menu.soup!="Nema"%><h3> <%=@today.menu.soup.humanize%>: <%=@today.soup%> </h3><%end%>
    <%if @today.menu.main_course!="Nema"%><h3> <%=@today.menu.main_course%>: <%=@today.main_course%> </h3><%end%>
    <%if @today.menu.side1!="Nema"%><h3> <%=@today.menu.side1%>: <%=@today.side1%> </h3><%end%>
    <%if @today.menu.side2!="Nema"%><h3> <%=@today.menu.side2%>: <%=@today.side2%> </h3><%end%>
    <%if @today.cabbage%><h3> Kupus: <%=@today.cabbage%> </h3><%end%>
    <%if @today.lettuce%><h3> Zelena salata: <%=@today.lettuce%> </h3><%end%>
    <%if @today.beetroot%><h3> Cikla: <%=@today.beetroot%> </h3><%end%>
    <%if @today.bread%><h3> Kruh: <%=@today.bread%> </h3><%end%>
  <%end%>
  </br>
  <h2>Potrošeno ovaj mjesec: <%=@month%> kn</h2>
</div>