config/routes.rb
Rails.application.routes.draw do
  resources :menu_orders
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :menus
  resources :menu_orders do
    put :update_attribute, defaults: { format: 'js' }
  end

  get 'employees', to: 'views#employees'
  get 'calculation', to: 'views#calculation'
  get 'info', to: 'views#info'
  put 'views/update_employee', to: 'views#update_employee'
  delete 'views/delete_employee', to: 'views#delete_employee'

  root to: 'views#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Narudžba Ručka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <ul>
      <% if employee_signed_in? %>
        <li>
          <%= link_to('Odjava', destroy_employee_session_path, method: :delete) %>        
        </li>
        <% if !current_employee.admin?%>
          <li>
            <%= link_to('Uredi Profil', edit_employee_registration_path(current_employee)) %>        
          </li>          
          <li>
            <%= link_to('Moguće narudžbe', root_path) %>        
          </li>          
          <li>
            <%= link_to('Današnja narudžba', info_path) %>        
          </li>
        <%end%>
        <% if current_employee.admin? %>
        <li>
          <%= link_to('Meniji', menus_path) %>        
        </li>
        <li>
          <%= link_to('Korisnici', employees_path) %>        
        </li>
        <li>
          <%= link_to('Obračun', calculation_path) %>        
        </li>
        <% end %>
      <% else %>
        <li>
        <%= link_to('Prijava', new_employee_session_path) %>  
        </li>
      <% end %>
    </ul>
  </head>

  <body>

    <%= yield %>
  </body>
</html>